import type { SystemStatus } from '@/lib/admin-data'
import { friendlyDateTime } from '@/lib/util'

function hoursSince(iso: string | null): number | null {
  if (!iso) return null
  return (Date.now() - new Date(iso).getTime()) / 3_600_000
}

/** Read-only panel: is the Mac engine keeping Supabase fresh? */
export function AdminStatus({ status }: { status: SystemStatus }) {
  const dayH = hoursSince(status.dayLastRefreshed)
  const briefH = hoursSince(status.briefingCreatedAt)

  const cards = [
    {
      label: "Day's View last refreshed",
      value: status.dayLastRefreshed ? friendlyDateTime(status.dayLastRefreshed) : 'never',
      warn: dayH === null || dayH > 30,
    },
    {
      label: 'Latest briefing',
      value: status.briefingLatestDate ?? 'none',
      sub: status.briefingCreatedAt ? `built ${friendlyDateTime(status.briefingCreatedAt)}` : null,
      warn: briefH === null || briefH > 30,
    },
    {
      label: 'Task-suggestion scan',
      value: status.suggestionStatus ?? 'idle',
      sub: status.suggestionLastScanned
        ? `last scan ${friendlyDateTime(status.suggestionLastScanned)}`
        : null,
      warn: false,
    },
    {
      label: 'Open tasks',
      value: String(status.openTasks),
      warn: false,
    },
  ]

  return (
    <section>
      <h2 className="mb-2 text-sm font-semibold">System status</h2>
      <div className="grid grid-cols-1 gap-3 sm:grid-cols-2">
        {cards.map((c) => (
          <div
            key={c.label}
            className={`rounded-xl border p-3 ${
              c.warn
                ? 'border-amber-400/50 bg-amber-50 dark:border-amber-500/30 dark:bg-amber-500/10'
                : 'border-black/10 dark:border-white/10'
            }`}
          >
            <p className="text-[11px] font-medium tracking-wide text-black/40 uppercase dark:text-white/40">
              {c.label}
            </p>
            <p className="mt-0.5 text-sm font-medium">
              {c.value}
              {c.warn && (
                <span className="ml-1 text-amber-600 dark:text-amber-400">· stale?</span>
              )}
            </p>
            {c.sub && <p className="text-[11px] text-black/40 dark:text-white/40">{c.sub}</p>}
          </div>
        ))}
      </div>
      <p className="mt-2 text-[11px] text-black/40 dark:text-white/40">
        Content is generated by Claude Code on the Mac engine. A &ldquo;stale?&rdquo; flag means the
        Mac may be off or a connector dropped — the site itself is fine.
      </p>
    </section>
  )
}
